# yaml-language-server: $schema=../schemas/rag_agent_config_schema.yaml
AgentConfiguration:
  config_version: 1.0
  agent_name: "rag_agent"
  model_name: "gpt-4o"
  model_version: "2024-05-13"
  model_deployment: "gpt-4o-2"
  model_deployment_endpoint: "https://openai-australia-east-303474.openai.azure.com/openai/deployments/gpt-4o-2/chat/completions?api-version=2024-08-01-preview"
  openai_api_version: "2024-08-01-preview"
  retrieval: 
      search_type: "hybrid"
      top_k: 3
  model_parameters:
    temperature: 0.0
    seed: 42
  intent_system_prompt: > 
        Your task is to extract the user’s intent by reformulating their latest question into a standalone query that is understandable without prior chat history. 
        Analyze the conversation to identify any contextual references in the latest question, and incorporate necessary details to make it self-contained. 
        Ensure the reformulated question preserves the original intent. Do not provide an answer; only return the reformulated question. 
        For example, if the latest question is ‘What about its pricing?’ and the chat history discusses Microsoft Azure, reformulate it to ‘What is the pricing of Microsoft Azure?’

  chat_system_prompt: > 
        You are a knowledgeable assistant specializing only in Microsoft technologies, including Azure, Microsoft Fabric, Microsoft 365, Dynamics 365, Power Platform. 
        Your responses should be based exclusively on the context provided in the prompt; do not incorporate external knowledge. 
        Address only questions related to Microsoft technologies. Deliver concise and clear answers, emphasizing the main points of the user’s query.
        If the provided context is insufficient to answer the question, request additional information.
            
        <context>
        {context}
        </context>"

  human_template: "question: {input}"
  #this parameter is deprecated in next version
  application_version: "1.0"   #- this parameter must be on application level configuration
  #this parameter is deprecated in next version
  application_name: "rag_llmops_workshop" #- this parameter must be on application level configuration
  
